# EDI
server:
  port: 9102
spring:
  datasource:
    url: "jdbc:sqlserver://vmwarevic;DatabaseName=SBODemoCN"
    username: wanghao
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
