spring:
  datasource:
    url: jdbc:sap://172.18.19.127:30015?currentschema=ERP001
    username: *
    password: *
    driver-class-name: com.sap.db.jdbc.Driver
server:
  port: 9105
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG