spring:
  datasource:
    url: jdbc:sap://172.18.19.127:30015?currentschema=ERP001
    username: SYSTEM
    password: Fanuc2019
    driver-class-name: com.sap.db.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
server:
  port: 9109
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
company:
  companydb: ERP001
  companyuser: BJ-FANUC\bfm004
  sessionurl: http://172.18.19.130:9111/v1/servicelayersession
  servicelayerurl: https://172.18.19.127:50000/b1s/v1
