spring:
  datasource:
    url: jdbc:sap://172.18.19.127:30015?currentschema=ERP001_TEST
    username: !@#
    password: *
    driver-class-name: com.sap.db.jdbc.Driver
server:
  port: 9108
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
company:
  companydb: ERP001_TEST
  companyuser: BJ-FANUC\ntc003
  sessionurl: http://172.18.19.131:9111/v1/servicelayersession
  servicelayerurl: https://172.18.19.127:50000/b1s/v1