spring:
  datasource:
    url: jdbc:sap://172.18.19.127:30015?currentschema=ERP001
    username: SYSTEM
    password: Fanuc2019
    driver-class-name: com.sap.db.jdbc.Driver
  aop:
    proxy-target-class: true
server:
  port: 9110
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
company:
  companydb: ERP001
  companyuser: BJ-FANUC\bfm004
  sessionurl: http://localhost/v1/servicelayersession
  servicelayerurl: https://172.18.19.127:50000/b1s/v1